# variable precedence
# CLI Level
# Task Level
# Role Level
# Play Level

- name: Demo Variable
  hosts: localhost
  connection: local
  vars:
    a: 100
  roles:
    - sample
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: a - {{ a }}
    - name: Declare variable in task level
      vars:
        a: 200
      ansible.builtin.debug:
        msg: a - {{ a }}

